replaceAll は使うことが出来ない
lib/diary/Scraper.ts:24:68 - error TS2550:
Property 'replaceAll' does not exist on type 'string'.
Do you need to change your target library?
Try changing the 'lib' compiler option to 'es2021' or later.

という感じでエラーが出る。
tsconfig で設定してもエラーが解消しなかったので利用を諦めた。